// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/backtest": {
            "post": {
                "description": "파라미터를 Python 엔진으로 전달하여 백테스트 결과(수익률 곡선 등)를 받아옵니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backtest"
                ],
                "summary": "퀀트 백테스트 실행",
                "parameters": [
                    {
                        "description": "백테스트 설정 (Ticker 및 전략 파라미터)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.BacktestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "수익률 데이터 및 날짜 배열",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Engine connection failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/list": {
            "get": {
                "description": "DB에 저장된 중복 없는 종목 심볼 목록을 조회합니다. 검색창의 자동완성(Autocomplete) 기능에 사용됩니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "종목 리스트 조회 (자동완성용)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_controller.StockItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/{symbol}/history": {
            "get": {
                "description": "특정 심볼의 회사명과 과거 시세 데이터를 조회합니다. (없으면 자동 수집)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "주식 히스토리 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock Symbol (e.g., NVDA)",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.StockHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_controller.StockItem": {
            "type": "object",
            "properties": {
                "symbol": {
                    "type": "string",
                    "example": "NVDA"
                }
            }
        },
        "quant-server_internal_model.BacktestRequest": {
            "type": "object"
        },
        "quant-server_internal_model.MarketData": {
            "description": "개별 일자의 시가, 고가, 저가, 종가 및 거래량 정보",
            "type": "object",
            "properties": {
                "bb_l": {
                    "type": "number",
                    "example": 139.8
                },
                "bb_m": {
                    "type": "number",
                    "example": 150
                },
                "bb_u": {
                    "type": "number",
                    "example": 160.2
                },
                "close": {
                    "type": "number",
                    "example": 153.4
                },
                "high": {
                    "type": "number",
                    "example": 155.8
                },
                "low": {
                    "type": "number",
                    "example": 149.1
                },
                "macd": {
                    "type": "number",
                    "example": 1.25
                },
                "macd_h": {
                    "type": "number",
                    "example": 0.45
                },
                "open": {
                    "type": "number",
                    "example": 150.25
                },
                "rsi": {
                    "description": "보조지표 필드",
                    "type": "number",
                    "example": 55.42
                },
                "time": {
                    "type": "string",
                    "example": "2026-02-01"
                },
                "volume": {
                    "type": "number",
                    "example": 1200500
                }
            }
        },
        "quant-server_internal_model.StockHistoryResponse": {
            "description": "주식의 기본 정보와 과거 시세 데이터를 포함합니다.",
            "type": "object",
            "properties": {
                "symbol": {
                    "type": "string",
                    "x-order": "1",
                    "example": "NVDA"
                },
                "company_name": {
                    "type": "string",
                    "x-order": "2",
                    "example": "NVIDIA Corporation"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/quant-server_internal_model.MarketData"
                    },
                    "x-order": "3"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Quant Trading API",
	Description:      "Go + Python 퀀트 플랫폼 API 서버입니다.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
