// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/backtest": {
            "post": {
                "description": "파라미터를 Python 엔진으로 전달하여 백테스트 결과(수익률 곡선 등)를 받아옵니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backtest"
                ],
                "summary": "퀀트 백테스트 실행",
                "parameters": [
                    {
                        "description": "백테스트 설정 (Ticker 및 전략 파라미터)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.BacktestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "수익률 데이터 및 날짜 배열",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Engine connection failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/paper/balance": {
            "get": {
                "description": "KIS Open API로 잔고와 보유종목을 조회합니다. 모의/실전 분기는 엔진의 KIS_MODE 환경변수가 결정합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "모의투자 계좌 잔고 조회 (KIS API 엔진 프록시)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/paper/orders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "모의투자 주문/체결 내역 (KIS API 엔진 프록시)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "YYYYMMDD — 생략 시 오늘",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYYMMDD — 생략 시 오늘",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "{ symbol, qty, side: buy|sell, order_type: market|limit, price? }",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "모의투자 주문 (KIS API 엔진 프록시)",
                "parameters": [
                    {
                        "description": "주문 payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/paper/quote/{symbol}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "국내주식 현재가 (KIS API 엔진 프록시)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "6자리 숫자 코드 또는 .KS/.KQ suffix 포함",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/portfolio/backtest": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "포트폴리오 백테스트 실행 (엔진 프록시)",
                "parameters": [
                    {
                        "description": "Backtest request (universe, clauses, max_positions, start_date, end_date)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/portfolio/rules": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "포트폴리오 룰셋 목록 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/quant-server_internal_model.PortfolioRule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "포트폴리오 룰셋 생성",
                "parameters": [
                    {
                        "description": "룰셋 payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.PortfolioRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.PortfolioRule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/portfolio/rules/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "포트폴리오 룰셋 수정",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "룰셋 payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.PortfolioRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.PortfolioRule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "portfolio"
                ],
                "summary": "포트폴리오 룰셋 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/portfolio/screen": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "포트폴리오 스크리닝 실행 (엔진 프록시)",
                "parameters": [
                    {
                        "description": "Screen request (universe, clauses, max_positions, as_of)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/list": {
            "get": {
                "description": "DB에 저장된 중복 없는 종목 심볼 목록을 조회합니다. 검색창의 자동완성(Autocomplete) 기능에 사용됩니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "종목 리스트 조회 (자동완성용)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_controller.StockItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/search": {
            "get": {
                "description": "symbol 또는 회사명(영문·한국어)에 q가 포함된 종목을 랭킹 순으로 반환합니다. 순위: 완전일치 \u003e symbol 접두사 \u003e name 접두사 \u003e symbol 부분일치 \u003e name 부분일치.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "종목 자동완성 검색",
                "parameters": [
                    {
                        "type": "string",
                        "description": "검색어 (symbol 또는 회사명 일부)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "최대 반환 개수 (기본 20, 최대 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_controller.StockSearchItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/{symbol}/history": {
            "get": {
                "description": "특정 심볼의 회사명과 과거 시세 데이터를 조회합니다. (없으면 자동 수집)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "주식 히스토리 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock Symbol (e.g., NVDA)",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.StockHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/{symbol}/intraday": {
            "get": {
                "description": "특정 심볼의 1분봉(Intraday) 시세 데이터를 조회합니다. (없으면 자동 수집)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "1분봉 시세 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock Symbol (e.g., NVDA)",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "가져올 데이터 갯수 (기본값: 1000)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/quant-server_internal_model.IntradayCandle"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_controller.StockItem": {
            "type": "object",
            "properties": {
                "symbol": {
                    "type": "string",
                    "example": "NVDA"
                }
            }
        },
        "internal_controller.StockSearchItem": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Rocket Lab Corporation"
                },
                "symbol": {
                    "type": "string",
                    "example": "RKLB"
                }
            }
        },
        "quant-server_internal_model.BacktestRequest": {
            "type": "object"
        },
        "quant-server_internal_model.IntradayCandle": {
            "description": "실시간 트레이딩 차트(Lightweight Charts)를 위한 1분봉 OHLCV 데이터",
            "type": "object",
            "properties": {
                "close": {
                    "type": "number",
                    "example": 15.4
                },
                "high": {
                    "type": "number",
                    "example": 15.8
                },
                "low": {
                    "type": "number",
                    "example": 14.9
                },
                "open": {
                    "type": "number",
                    "example": 15.25
                },
                "symbol": {
                    "type": "string",
                    "example": "RKLB"
                },
                "time": {
                    "type": "integer",
                    "example": 1700000000
                },
                "volume": {
                    "type": "number",
                    "example": 12500
                }
            }
        },
        "quant-server_internal_model.MarketData": {
            "description": "개별 일자의 시가, 고가, 저가, 종가 및 거래량 정보",
            "type": "object",
            "properties": {
                "bb_l": {
                    "type": "number",
                    "example": 139.8
                },
                "bb_m": {
                    "type": "number",
                    "example": 150
                },
                "bb_u": {
                    "type": "number",
                    "example": 160.2
                },
                "close": {
                    "type": "number",
                    "example": 153.4
                },
                "high": {
                    "type": "number",
                    "example": 155.8
                },
                "low": {
                    "type": "number",
                    "example": 149.1
                },
                "macd": {
                    "type": "number",
                    "example": 1.25
                },
                "macd_h": {
                    "type": "number",
                    "example": 0.45
                },
                "open": {
                    "type": "number",
                    "example": 150.25
                },
                "rsi": {
                    "description": "보조지표 필드",
                    "type": "number",
                    "example": 55.42
                },
                "time": {
                    "type": "string",
                    "example": "2026-02-01"
                },
                "volume": {
                    "type": "number",
                    "example": 1200500
                }
            }
        },
        "quant-server_internal_model.PortfolioRule": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "quant-server_internal_model.PortfolioRuleRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "오버솔드 리버설"
                }
            }
        },
        "quant-server_internal_model.StockHistoryResponse": {
            "description": "주식의 기본 정보와 과거 시세 데이터를 포함합니다.",
            "type": "object",
            "properties": {
                "symbol": {
                    "type": "string",
                    "x-order": "1",
                    "example": "NVDA"
                },
                "company_name": {
                    "type": "string",
                    "x-order": "2",
                    "example": "NVIDIA Corporation"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/quant-server_internal_model.MarketData"
                    },
                    "x-order": "3"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Quant Trading API",
	Description:      "Go + Python 퀀트 플랫폼 API 서버입니다.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
