// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/backtest": {
            "post": {
                "description": "파라미터를 Python 엔진으로 전달하여 백테스트 결과(수익률 곡선 등)를 받아옵니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backtest"
                ],
                "summary": "퀀트 백테스트 실행",
                "parameters": [
                    {
                        "description": "백테스트 설정 (Ticker 및 전략 파라미터)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quant-server_internal_model.BacktestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "수익률 데이터 및 날짜 배열",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Engine connection failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stocks/{symbol}/history": {
            "get": {
                "description": "특정 심볼의 과거 시세 데이터를 조회합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "주식 히스토리 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock Symbol (e.g., RKLB)",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/quant-server_internal_model.MarketData"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "quant-server_internal_model.BacktestRequest": {
            "type": "object"
        },
        "quant-server_internal_model.MarketData": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number",
                    "example": 114.1
                },
                "high": {
                    "type": "number",
                    "example": 115.2
                },
                "low": {
                    "type": "number",
                    "example": 111.05
                },
                "open": {
                    "type": "number",
                    "example": 112.5
                },
                "symbol": {
                    "type": "string",
                    "example": "NVDA"
                },
                "time": {
                    "type": "string",
                    "example": "2025-01-25"
                },
                "volume": {
                    "type": "number",
                    "example": 1200000
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Quant Trading API",
	Description:      "Go + Python 퀀트 플랫폼 API 서버입니다.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
